spring:
  jpa:
    show-sql: true               # SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true          # SQL 로그 포맷 설정
    ddl-auto: update             # 스키마 업데이트 자동화
    defer-datasource-initialization: true  # 데이터베이스 초기화 지연

  datasource:
    url: jdbc:h2:mem:test       # 인메모리 H2 데이터베이스 사용
    driver-class-name: org.h2.Driver
    username: sm                  # H2 기본 사용자 이름
    password: sm                  # 비밀번호 설정 (기본적으로 비밀번호가 없으면 빈칸으로 두기)

  h2:
    console:
      enabled: true               # H2 콘솔 활성화 (브라우저에서 H2 데이터베이스 접근 가능)
      path: /h2-console            # H2 콘솔의 경로
